# Generated by Django 2.2.2 on 2019-07-09 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliablehour',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 781909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avaliablehour',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 781887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 780859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 780829, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 777798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 777761, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 779293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 779264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 782395, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 782373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enrrollment',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 780115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enrrollment',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 780079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 776147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 776102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 776836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 776797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 781516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 781500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 781443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 781468, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 778599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 778572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentvote',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 782845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentvote',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 4, 46, 10, 782823, tzinfo=utc)),
        ),
    ]
