# Generated by Django 2.2.2 on 2019-07-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_auto_20190725_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='from_date_vote',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='until_date_vote',
        ),
    ]
