# Generated by Django 2.2.2 on 2019-07-09 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0003_auto_20190709_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliablehour',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 865489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avaliablehour',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 865467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 864541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 864522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 862636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 862616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 863519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 863500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 865996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 865973, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enrrollment',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 864048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enrrollment',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 864025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 861748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 861723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 862117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 862095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 865090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 865070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 865018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 865041, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 863109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 863092, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentvote',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 866445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentvote',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 866422, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ProfessorVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 866898, tzinfo=utc))),
                ('date_mod', models.DateTimeField(default=datetime.datetime(2019, 7, 9, 5, 49, 24, 866920, tzinfo=utc))),
                ('state', models.BooleanField(default=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.Professor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.CourseSchedule')),
            ],
            options={
                'unique_together': {('professor', 'schedule')},
            },
        ),
    ]
