# Generated by Django 2.2.2 on 2019-07-28 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0005_auto_20190727_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='from_date_vote',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='until_date_vote',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='from_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='until_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('avaliable', 'course')},
        ),
    ]
