# Generated by Django 2.2.2 on 2019-07-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0006_auto_20190728_0821'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='secretary',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
