# Generated by Django 2.2.2 on 2019-07-18 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0006_auto_20190718_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliablehour',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 52900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='avaliablehour',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 52877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 51996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 51977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 50037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 50018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 50908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 50889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 53392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 53369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enrrollment',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 51435, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enrrollment',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 51411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 49143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 49118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='professorvote',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 54453, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='professorvote',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 54428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 49594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 49574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 52515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 52499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_from',
            field=models.TimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 52443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_to',
            field=models.TimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 52466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 50505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 50488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentvote',
            name='date_mod',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 53881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentvote',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 23, 49, 41, 53858, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('classroom_id', 'faculty')},
        ),
    ]
