# Generated by Django 2.2.2 on 2019-07-29 02:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0007_auto_20190728_2056'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='secretary',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
